spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo_dev_db
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
